--Artist
-- 1)
-- INSERT INTO artist (name)
-- VALUES --('FLORIDA GEORGIA LINE'),
-- ('LUKE COMBS'),
-- ('MORGAN WALLEN');
-- SELECT * FROM artist;
-- 2)
-- SELECT * FROM artist
-- ORDER BY name DESC
-- OFFSET 60
-- LIMIT 10;
-- 3)
-- SELECT * FROM artist
-- ORDER BY name
-- OFFSET 200
-- LIMIT 5;
-- 4)
-- SELECT * FROM artist
-- WHERE name LIKE ('Black%');
-- 5)
-- SELECT * FROM artist
-- WHERE name LIKE ('%Black%');